export const CONFIG = {
  lanes: [-2.5, 0, 2.5],
  chunkLength: 30,
  chunkCount: 5,
  recycleZ: 15,
  farZ: -135,
  laneLerp: 12,
  tiltMax: Math.PI / 12, // 15 degrees
  gravity: -28,
  jumpVelocity: 9.5,
  slideDuration: 0.75,
  slideImpulse: -18,
  playerHeight: 1.7,
  playerHalfWidth: 0.35,
  slideHeightFactor: 0.5,
  speedStart: 8,
  speedMax: 26,
  speedAccel: 0.15,
  scorePerUnit: 1,
  coinScore: 25,
  multInterval: 30,
  multMax: 10,
  highScoreKey: 'railway-rush-highscore-v1',
  deltaClamp: 0.05,
  zoneNear: -5,
  zoneFar: 5,
  gantrySpacing: 25,
  hudHz: 10,
  coinParticleCount: 64,
  dustParticleCount: 32,
  reactionGapMin: 22, // world units of empty track between obstacle groups, scaled by speed
}
